### ISSUE TITLE
Cannot retrieve solutions from GitHub

### ISSUE THREAD

**Issue by rappen** [rajyraman/Solution-Installer-for-XrmToolBox#6]
Clicking "Retrieve Solutions" and it gives error "One or more errors occurred."

![image](https://user-images.githubusercontent.com/2572253/74191955-e0c21100-4c54-11ea-8979-5eeb3fff0fec.png)

Can't find any log file for the tool.

---
- Deployment: Online
- DB Version: 9.1.0.12935
- XTB Version: 1.2020.2.36
- Tool Version: 1.2018.5.5

**Comment by rajyraman** [comment]
@rappen - Andrew changed his GitHub username from a33ik to AndrewButenko. Fixed it in the db.json. Should work now.

**Comment by rappen** [comment]
How smooth was that?!?
Totally impressed.
And let's blame @AndrewButenko 😁

**Comment by AndrewButenko** [comment]
> How smooth was that?!?
> Totally impressed.
> And let's blame @AndrewButenko 😁

Yes. I'm the person to blame :)
