### ISSUE TITLE
Unable to access solutions

### ISSUE THREAD

**Issue by ashwinravi** [rajyraman/Solution-Installer-for-XrmToolBox#7]
Even after entering the Github API key, I get an error when trying to retrieve solutions from Github. It returns a generic error "One or more errors occurred". In the bottom right, I see a message showing "Retrieved 13 solutions from Github".
![image](https://user-images.githubusercontent.com/2646050/98064085-53d46e80-1e06-11eb-85e8-73366d49a5aa.png)

**Comment by rajyraman** [comment]
@ashwinravi - Ramon Tebar changed his GitHub username. I have updated it now with the correct username. Please try again.

**Comment by ashwinravi** [comment]
@rajyraman That fixed it. Can you tell me what you did to fix it in case this happens again?
Also, where is that db.json file located that I believe this reads from?

**Comment by rajyraman** [comment]
Updated this file. https://www.github.com/rajyraman/Solution-Installer-for-XrmToolBox/tree/master/db.json

**Comment by ashwinravi** [comment]
Yep I just noticed that as well. I thought that resided in the local XrmToolbox storage location on my machine.

**Comment by ashwinravi** [comment]
How does it pick up the latest db.json automatically without updating the tool version?

**Comment by rajyraman** [comment]
It reads it from the repo itself using GitHub API.
